### ISSUE TITLE
specifying --uefistub in preset has no effect

### ISSUE THREAD

**Issue by benniekiss** [archlinux/mkinitcpio#105]
When creating a unified kernel image with a preset in `/etc/mkinitcpio.d/unified.preset` for a kernel with a custom install location, specifying `--uefistub` in `PRESET_options=` has no effect. I believe the reason is in https://github.com/archlinux/mkinitcpio/blob/a72cc79561572c11082408a8e31bce51decbe018/mkinitcpio line 562, it shows `_optkernelimage` when I believe it should be `_optuefistub`

**Comment by Foxboron** [comment]
https://github.com/archlinux/mkinitcpio/pull/80

**Comment by benniekiss** [comment]
forgot to check for related issues. Thank you!
