### ISSUE TITLE
dracut hooks

### ISSUE THREAD

**Issue by udeved** [archlinux/mkinitcpio#11]
Hi @grazzolini 

I have been following the public arch ML on dracut.

Sorry for opening an issue in mkinitcpio, I have made experimental dracut hooks derived from the mkinitcpio hooks.

You can view them here, perhaps they have some value to your dracut hooks:
https://gitea.artixlinux.org/packagesD/dracut/src/branch/master/trunk

These hooks don't use any preset file, they generate the presets on the fly.

**Comment by grazzolini** [comment]
@udeved, given this is the mkinitcpio repo, can you please send this to the archlinux-projects mailing list or open a dracut bug on bugs.archlinux.org pointing to the link or attaching the files?

**Comment by udeved** [comment]
Ok, fine with me, now that I know where to send it.

The hooks have certainly room for improvement, they are rather rough, but they do work. Currently testing a dracut iso with them.

Kind of difficult to contribute, I tried via public email, but had no reply.

**Comment by grazzolini** [comment]
@udeved, to which email did you send it? We don't have an easy way to provide patches to packages, unfortunately. I just want to keep the mkinitcpio repository clear. Please, open a bug report and send to my email directly the link.

**Comment by udeved** [comment]
@grazzolini 

I tried via public ML, iirc email at aaron, but these were the old hooks when the hooks were still in the kernel.

I'll open a bug report and send you the link directly as well.

Close the naughty foreign issue. :)

**Comment by udeved** [comment]
May I propose a alpm hook repo with pkg name sub folders which can receive contribs via PR?

**Comment by grazzolini** [comment]
@udeved, if you want to create a repo like that on your account, sure. I don't plan to create one on the official archlinux space for now. We are however toying with gitlab to, perhaps some day, have PR's for packages as well.

**Comment by eli-schwartz** [comment]
Aaron deals with IP and trademark stuff primarily these days... he isn't an active day to day packager, and is definitely the wrong person to reach out to about packaging changes. :p

**Comment by udeved** [comment]
@eli-schwartz 

his email pops up when ou try to get write access to the public ML.
It states to send applications to this email, perhaps something to check and update?

**Comment by eli-schwartz** [comment]
Which ML? arch-general is available to any subscriber. arch-dev-public is forbidden to anyone other than archlinux staffers, no exceptions and no applications...

**Comment by udeved** [comment]
I tried iirc arch-dev-public, since this is where the dracut and mkinitcpio is discussed, and it somewhere staes temporary access can be granted.
I got a bit frustrated with the complicated or unknown procedure to reply, just trying to share working dracut hook.
