### ISSUE TITLE
UEFI stub: Unable to write to <path>

### ISSUE THREAD

**Issue by rogueai** [archlinux/mkinitcpio#111]
Hi, I'm trying to generate a recovery efi image from a read-only btrfs snapshot, but it fails with the following:
```
❯ sudo mkinitcpio -p linux-recovery                     
==> Building image from preset: /etc/mkinitcpio.d/linux-recovery.preset: 'recovery'
  -> -k /.snapshots/1/snapshot/boot/vmlinuz-linux -c /etc/mkinitcpio.conf -g /.snapshots/1/snapshot/boot/initramfs-linux.img --splash /usr/share/systemd/bootctl/splash-arch.bmp --cmdline /etc/kernel/cmdline-recovery -U /efi/EFI/arch_recovery/arch-linux-recovery.efi --microcode /.snapshots/1/snapshot/boot/intel-ucode.img
==> ERROR: Unable to write to /.snapshots/1/snapshot/boot/initramfs-linux.img
```
Here's my preset config:
```
ALL_config="/etc/mkinitcpio.conf"
ALL_kver="/.snapshots/1/snapshot/boot/vmlinuz-linux"
ALL_microcode=(/.snapshots/1/snapshot/boot/*-ucode.img)

PRESETS=('recovery')

#recovery_config="/etc/mkinitcpio.conf"
recovery_image="/.snapshots/1/snapshot/boot/initramfs-linux.img"
recovery_efi_image="/efi/EFI/arch_recovery/arch-linux-recovery.efi"
recovery_options="--splash /usr/share/systemd/bootctl/splash-arch.bmp --cmdline /etc/kernel/cmdline-recovery"
```

I've tried playing around with the `-g` parameter, but with no luck.

Thanks!

**Comment by rogueai** [comment]
Ok I now understand this was partially my fault, in the sense that `recovery_image` is generated as part of the build and then used to build the efi image, changing `recovery_image` to something like `/tmp/initramfs-linux.img` worked, I wonder though if it's possible to have mkinitcpio generate the img to a temp location in the case of uefi stubs?

**Comment by Foxboron** [comment]
@rogueai is this still the case with the recent `mkinitcpio` release?

**Comment by rogueai** [comment]
Hi, I just tested removing the `<preset>_image` config option and it works, thanks!

**Comment by Foxboron** [comment]
Fixed with https://github.com/archlinux/mkinitcpio/commit/6009499a39475989f491ddd5c38e7e277e07ef77
