### ISSUE TITLE
Support signing the kernel and/or initramfs/microcode (secure boot)

### ISSUE THREAD

**Issue by klausenbusk** [archlinux/mkinitcpio#12]
If people want to use Secure Boot with there own keys the kernel (and preferable also the initramfs, cmdline and microcode) needs to be signed.

The can be done with a custom hook like this:
```
[Trigger]
Operation = Install
Operation = Upgrade
Type = Package
Target = linux

[Action]
Description = Signing Kernel for SecureBoot
When = PostTransaction
Exec = /usr/bin/sbsign --key /root/db.key --cert /root/db.crt /boot/vmlinuz-linux
```
Would it make sense to support this out-of-the-box? Something like this:
```patch
diff --git a/libalpm/scripts/mkinitcpio-install b/libalpm/scripts/mkinitcpio-install
index d2e5041..213c174 100644
--- a/libalpm/scripts/mkinitcpio-install
+++ b/libalpm/scripts/mkinitcpio-install
@@ -30,6 +30,11 @@ while read -r line; do
     # always install the kernel
     install -Dm644 "${line}" "/boot/vmlinuz-${pkgbase}"
 
+    # sign the kernel
+    if [[ -n "$secureboot_db_key" && -n "$secureboot_db_key" ]]; then
+      sbsign --key "${secureboot_db_key}" --cert "${secureboot_db_key}" "/boot/vmlinuz-${pkgbase}"
+    fi
+
     # compound args for each kernel
     args+=(-p "${pkgbase}")
 done
diff --git a/mkinitcpio.d/hook.preset b/mkinitcpio.d/hook.preset
index 66709a8..d04d035 100644
--- a/mkinitcpio.d/hook.preset
+++ b/mkinitcpio.d/hook.preset
@@ -12,3 +12,6 @@ default_image="/boot/initramfs-%PKGBASE%.img"
 #fallback_config="/etc/mkinitcpio.conf"
 fallback_image="/boot/initramfs-%PKGBASE%-fallback.img"
 fallback_options="-S autodetect"
+
+#secureboot_db_key=""
+#secureboot_db_cert=""
```

[Ideally](https://mjg59.dreamwidth.org/48897.html) we should also sign the initramfs (+ microcode) and cmdline, which can be done by using the `systemd` efi stub, but I'm not sure how to do that cleanly:
```shell
cat /boot/intel-ucode.img /boot/initramfs-linux.img > initramfs.img

objcopy \
  --add-section .osrel=/etc/os-release --change-section-vma .osrel=0x20000 \
  --add-section .cmdline=/etc/cmdline --change-section-vma .cmdline=0x30000 \
  --add-section .linux=/boot/vmlinuz-linux --change-section-vma .linux=0x2000000 \
  --add-section .initrd=initramfs.img --change-section-vma .initrd=0x3000000 \
  "/usr/lib/systemd/boot/efi/linuxx64.efi.stub" kernel.efi
```

Links:  
https://wiki.archlinux.org/index.php/Secure_Boot#Using_your_own_keys  
https://bentley.link/secureboot/

**Comment by Foxboron** [comment]
Personally no. The `sbsign` stuff should not be a thing in the `mkinitcpio-install` hook. libalpm hooks are ordered, so you can provide your own hooks and people might not want to use `sbsign` at all.

As for efi stub generation, I have a WIP patch for it I have intended to fixup and submit.

https://github.com/Foxboron/mkinitcpio/commit/892848795b589e4c17c9a70d947e3fd5f1dfa7d4

**Comment by klausenbusk** [comment]
> Personally no. The sbsign stuff should not be a thing in the mkinitcpio-install hook. libalpm hooks are ordered, so you can provide your own hooks and people might not want to use sbsign at all.

..and people may not want to create a EFI image :) Would it make sense to add a `--sign` option to `mkinitcpio`?

> As for efi stub generation, I have a WIP patch for it I have intended to fixup and submit.

Can it be configured to create a efi stub without specifying `-U` (ex by tweaking a config file)? That could be useful so I don't need to create my own hook.

**Comment by Foxboron** [comment]
>..and people may not want to create a EFI image :) Would it make sense to add a --sign option to mkinitcpio?

I don't see why this needs to be a part of `mkinitcpio`. It's added complexity for something that doesn't need to be there and works completely fine being a separate hook.

>Can it be configured to create a efi stub without specifying -U (ex by tweaking a config file)? That could be useful so I don't need to create my own hook.

Add `-U` to `default_options` in `mkinitcpio.conf`

**Comment by klausenbusk** [comment]
> I don't see why this needs to be a part of `mkinitcpio`. It's added complexity for something that doesn't need to be there and works completely fine being a separate hook.

The same could be said regarding your EFI patch, but lets just agree to disagree :) (better EFI support is a bit more important than secure boot though)  
Anyways, I look forward to your EFI patch, it will simplify my hook.
> Add `-U` to `default_options` in `mkinitcpio.conf`

Thanks!

**Comment by grazzolini** [comment]
Ok, where did you get that, in order to use secure boot, the kernel, initramfs, cmdline and microcode **must** be signed? How does one even sign the kernel cmdline?

I use my own keys and I use [cryptboot](https://github.com/xmikos/cryptboot) to make my life easier. I could see these changes you presented belonging there, but not to mkinitcpio directly.

**Comment by Foxboron** [comment]
@grazzolini With an unencrypted boot partition, it has to be; yes. Else only the kernel is actually validated towards the keys.

**Comment by grazzolini** [comment]
@Foxboron, yes, but there's no **must**, only **should**. And while I, myself, use a an encrypted boot partition, I still sign most of the binaries.

I'm just not sure this belongs with mkinitcpio itself.

**Comment by Foxboron** [comment]
The signing part doesn't belong in `mkinitcpio`, but I strongly believe the EFI binary generation belongs.

**Comment by grazzolini** [comment]
@Foxboron, sure. I agree that mkinitcpio could in the future start creating EFI stubs. But that's not the subject of this issue.

And yes, nobody used **must**, but instead **needs to**.
