### ISSUE TITLE
Move project to Arch Linux's gitlab

### ISSUE THREAD

**Issue by dvzrv** [archlinux/mkinitcpio#120]
To align with our other internal projects, mkinitcpio should be moved to https://gitlab.archlinux.org/mkinitcpio/mkinitcpio, rendering the project on github only a mirror.

**Comment by anthraxx** [comment]
Is there a reason why we don't want this to be managed under our `archlinux` namespace? Our automatic access management and settings tools like gluebuddy only operate on the `archlinux` namespace. We should move `mkinitcpio` as a group under `archlinux` namely `archlinux/mkinitcpio/mkinitcpio`

**Comment by dvzrv** [comment]
I don't really mind where it ends up, as long as it ends up on our gitlab :)

**Comment by anthraxx** [comment]
It's still an arch linux project, repod and our keyringctl can be used outside of arch as well. This is not how we should categorize what to put into our namespace and what not. Any of our internal official projects should be under `archlinux`. We enforce certain settings like protected branches, we manage users to be in line with keycloak and ensure no unexpected people have write access etc.

**Comment by Foxboron** [comment]
We'll push this to `archlinux/mkinitcpio`, just to clear out any confusion or uncertainty.

**Comment by nl6720** [comment]
Closing in favor of https://gitlab.archlinux.org/archlinux/infrastructure/-/issues/474.
