### ISSUE TITLE
systemd warning because of /usr/local/bin symlink to /usr/bin

### ISSUE THREAD

**Issue by DaanDeMeyer** [archlinux/mkinitcpio#31]
See https://github.com/systemd/systemd/issues/15699

The warning seems to happen because /usr/local/bin is a symlink to /usr/bin and systemd is resolving symlinks for one path and not for another which leads to the warning `initrd-switch-root.service: Current command vanished from the unit file, execution of the command list won't be resumed.` when using systemd in the initramfs.

I'm leaning towards considering this a bug in systemd rather than mkinitcpio but does mkinitcpio actually gain something out of symlinking /usr/local/bin to /usr/bin? A quick grep through mkinitpcio and the core packages repository doesn't immediately yield any results on local/bin. 

I did a blame and the original commit message that adds the symlinks mentions the following:

>  This also symlinks /usr/local/{lib,bin} into the common /usr/lib and
    /usr/bin, respectively, so that there's always a way to override libs
    and bins, and they're automatically pulled into our strict early init
    path of /usr/bin.

**Comment by grazzolini** [comment]
This was fixed upstream, so closing here.
