### ISSUE TITLE
Add zstd compression supoort for initramfs

### ISSUE THREAD

**Issue by alvin998179** [archlinux/mkinitcpio#5]
Could you please add zstd compression supoort for initramfs?

**Comment by Foxboron** [comment]
No upstream support in the kernel for zstd compressed initramfs.

**Comment by alvin998179** [comment]
Thank you ! But dracut can.  How can it do that?

**Comment by Foxboron** [comment]
It assumes you have the needed patches.

**Comment by alvin998179** [comment]
Thank you a lot!

**Comment by jelly** [comment]
See https://www.mail-archive.com/arch-projects@archlinux.org/msg04706.html

**Comment by grazzolini** [comment]
@alexeicolin mkinitcpio has been tested with zstd and it works out of the box. The image is reproducible as well. But we need upstream support. If you patch your kernel, and change your mkinitcpio.conf to use COMPRESSION=zstd, it will work just fine.

**Comment by sirlucjan** [comment]
I'm sorry for digging up the old thread, but I confirm - with the right patches on:

https://github.com/sirlucjan/kernel-patches/tree/master/5.7/zstd-patches-sep

mkinitcpio handles zstd compression without problems.

**Comment by grazzolini** [comment]
Well, yes. I even acknowledge this in the very comment before closing this issue. mkinitcpio itself supports zstd just fine. The kernel, however, doesn't support it yet.

**Comment by bundi78** [comment]
starting with 5.9, the kernel has [zstd](https://kernelnewbies.org/LinuxChanges#Linux_5.9.Support_for_ZSTD_compressed_kernel.2C_ramdisk_and_initramfs).
