### ISSUE TITLE
Feature request: Install module but don't load

### ISSUE THREAD

**Issue by DocMAX** [archlinux/mkinitcpio#61]
Feature request: Install module but don't load.
I want to load the module by hook if some conditions are met.
Maybe a suffix like "?" would be nice.
MODULES=(one two !three) where three gets installed but not loaded

**Comment by grazzolini** [comment]
what is the use case for this?

**Comment by DocMAX** [comment]
Now long ago, don't rememer. But i had one. I'll close that.
